// Mock data for Brasil FC team management

export const teamInfo = {
  name: "Brasil FC",
  logoUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Logo_Brasil.png",
  founded: 2018,
  stadium: "Ciudadela México",
  city: "Buenos Aires",
  colors: ["Verde", "Amarillo", "Azul"],
  description:
    "El equipo del barrio, jugando con pasión y alegría. Representamos los colores de Brasil con orgullo en cada partido.",
  president: "Juan Silva",
  coach: "Roberto Carlos",
}

export const players = [
  {
    id: 1,
    name: "Carlos Rodríguez",
    number: 1,
    position: "Portero",
    age: 28,
    goals: 0,
    assists: 0,
    yellowCards: 2,
    redCards: 0,
    gamesPlayed: 15,
  },
  {
    id: 2,
    name: "Miguel Santos",
    number: 2,
    position: "Defensa",
    age: 25,
    goals: 1,
    assists: 3,
    yellowCards: 4,
    redCards: 0,
    gamesPlayed: 14,
  },
  {
    id: 3,
    name: "Diego Fernández",
    number: 3,
    position: "Defensa",
    age: 27,
    goals: 2,
    assists: 1,
    yellowCards: 3,
    redCards: 1,
    gamesPlayed: 13,
  },
  {
    id: 4,
    name: "Lucas Martínez",
    number: 4,
    position: "Defensa",
    age: 24,
    goals: 0,
    assists: 2,
    yellowCards: 5,
    redCards: 0,
    gamesPlayed: 15,
  },
  {
    id: 5,
    name: "Javier López",
    number: 5,
    position: "Defensa",
    age: 26,
    goals: 1,
    assists: 4,
    yellowCards: 2,
    redCards: 0,
    gamesPlayed: 14,
  },
  {
    id: 6,
    name: "Roberto García",
    number: 6,
    position: "Mediocampista",
    age: 23,
    goals: 3,
    assists: 7,
    yellowCards: 3,
    redCards: 0,
    gamesPlayed: 15,
  },
  {
    id: 7,
    name: "Fernando Silva",
    number: 7,
    position: "Mediocampista",
    age: 22,
    goals: 5,
    assists: 8,
    yellowCards: 1,
    redCards: 0,
    gamesPlayed: 14,
  },
  {
    id: 8,
    name: "Andrés Pérez",
    number: 8,
    position: "Mediocampista",
    age: 25,
    goals: 4,
    assists: 6,
    yellowCards: 2,
    redCards: 0,
    gamesPlayed: 13,
  },
  {
    id: 9,
    name: "Mateo Ramírez",
    number: 9,
    position: "Delantero",
    age: 24,
    goals: 12,
    assists: 3,
    yellowCards: 1,
    redCards: 0,
    gamesPlayed: 15,
  },
  {
    id: 10,
    name: "Gabriel Torres",
    number: 10,
    position: "Delantero",
    age: 26,
    goals: 10,
    assists: 9,
    yellowCards: 2,
    redCards: 0,
    gamesPlayed: 15,
  },
  {
    id: 11,
    name: "Pablo Morales",
    number: 11,
    position: "Delantero",
    age: 23,
    goals: 8,
    assists: 4,
    yellowCards: 1,
    redCards: 0,
    gamesPlayed: 14,
  },
]

export const matches = [
  {
    id: 1,
    date: "2025-01-15",
    time: "10:00",
    opponent: "Los Tigres FC",
    location: "Local",
    result: "Victoria",
    goalsFor: 3,
    goalsAgainst: 1,
    played: true,
  },
  {
    id: 2,
    date: "2025-01-22",
    time: "11:00",
    opponent: "Águilas United",
    location: "Visitante",
    result: "Empate",
    goalsFor: 2,
    goalsAgainst: 2,
    played: true,
  },
  {
    id: 3,
    date: "2025-01-29",
    time: "12:00",
    opponent: "Leones FC",
    location: "Local",
    result: "Victoria",
    goalsFor: 4,
    goalsAgainst: 0,
    played: true,
  },
  {
    id: 4,
    date: "2025-02-05",
    time: "13:00",
    opponent: "Pumas del Sur",
    location: "Visitante",
    result: "Derrota",
    goalsFor: 1,
    goalsAgainst: 2,
    played: true,
  },
  {
    id: 5,
    date: "2025-02-12",
    time: "14:00",
    opponent: "Halcones FC",
    location: "Local",
    result: "Victoria",
    goalsFor: 2,
    goalsAgainst: 1,
    played: true,
  },
  {
    id: 6,
    date: "2025-02-19",
    time: "10:00",
    opponent: "Cóndores United",
    location: "Visitante",
    result: "Victoria",
    goalsFor: 3,
    goalsAgainst: 2,
    played: true,
  },
  {
    id: 7,
    date: "2025-12-12",
    time: "10:30",
    opponent: "Jaguares FC",
    location: "Local",
    result: null,
    goalsFor: null,
    goalsAgainst: null,
    played: false,
  },
]

export const nextMatch = {
  id: 7,
  date: "2025-12-12",
  time: "10:30",
  opponent: "Jaguares FC",
  location: "Local",
  stadium: "Cancha Municipal",
  address: "Av. Principal 123, Buenos Aires",
}

export const callUp = [
  { playerId: 1, status: "Convocado" },
  { playerId: 2, status: "Convocado" },
  { playerId: 3, status: "Lesionado" },
  { playerId: 4, status: "Convocado" },
  { playerId: 5, status: "Convocado" },
  { playerId: 6, status: "Convocado" },
  { playerId: 7, status: "Convocado" },
  { playerId: 8, status: "Convocado" },
  { playerId: 9, status: "Convocado" },
  { playerId: 10, status: "Convocado" },
  { playerId: 11, status: "Suspendido" },
]

export const standings = [
  { position: 1, team: "Leones FC", played: 6, won: 5, drawn: 1, lost: 0, goalsFor: 15, goalsAgainst: 3, points: 16 },
  { position: 2, team: "Brasil FC", played: 6, won: 4, drawn: 1, lost: 1, goalsFor: 15, goalsAgainst: 8, points: 13 },
  {
    position: 3,
    team: "Águilas United",
    played: 6,
    won: 3,
    drawn: 2,
    lost: 1,
    goalsFor: 12,
    goalsAgainst: 7,
    points: 11,
  },
  {
    position: 4,
    team: "Pumas del Sur",
    played: 6,
    won: 3,
    drawn: 1,
    lost: 2,
    goalsFor: 10,
    goalsAgainst: 9,
    points: 10,
  },
  { position: 5, team: "Halcones FC", played: 6, won: 2, drawn: 2, lost: 2, goalsFor: 8, goalsAgainst: 8, points: 8 },
  {
    position: 6,
    team: "Los Tigres FC",
    played: 6,
    won: 2,
    drawn: 1,
    lost: 3,
    goalsFor: 7,
    goalsAgainst: 10,
    points: 7,
  },
  {
    position: 7,
    team: "Cóndores United",
    played: 6,
    won: 1,
    drawn: 1,
    lost: 4,
    goalsFor: 6,
    goalsAgainst: 12,
    points: 4,
  },
  { position: 8, team: "Jaguares FC", played: 6, won: 0, drawn: 1, lost: 5, goalsFor: 3, goalsAgainst: 19, points: 1 },
]

export const teamStats = {
  totalGames: 6,
  wins: 4,
  draws: 1,
  losses: 1,
  goalsFor: 15,
  goalsAgainst: 8,
  winPercentage: 66.7,
}
